name: Publish package
on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3.1.0
    - name: Set up JDK 15
      uses: actions/setup-java@v2.5.0
      with:
        java-version: 15.0.1
        distribution: 'zulu'

    - name: Build
      run: gradle build

    - name: Configure git
      run: |
        git config --local user.email "release@fluentlabs.io"
        git config --local user.name "Release"

    - name: Release
      run: gradle release -Prelease.useAutomaticVersion=true
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
