name: Gradle Package
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2.1.0
      with:
        java-version: 15.0.1
        distribution: 'zulu'

    - name: Build
      run: gradle build

    - name: Configure git
      run: |
        git config --local user.email "release@fluentlabs.io"
        git config --local user.name "Release"

    - name: Release
      run: gradle release -Prelease.useAutomaticVersion=true

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      run: gradle publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
