name: Pull request test

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v3.7.0
      with:
        java-version: 15.0.1
        distribution: 'zulu'

    - name: Build with Gradle
      run: gradle build
